apiVersion: batch/v1
kind: CronJob
metadata:
  name: namespace-auditor
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: namespace-auditor
          restartPolicy: Never
          containers:
            - name: auditor
              image: bryanpaget/namespace-auditor:latest
              env:
                - name: GRACE_PERIOD
                  valueFrom:
                    configMapKeyRef:
                      name: namespace-auditor-config
                      key: grace-period
                - name: ALLOWED_DOMAINS
                  valueFrom:
                    configMapKeyRef:
                      name: namespace-auditor-config
                      key: allowed-domains
                - name: AZURE_TENANT_ID
                  valueFrom:
                    secretKeyRef:
                      name: azure-creds
                      key: tenant-id
                - name: AZURE_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: azure-creds
                      key: client-id
                - name: AZURE_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: azure-creds
                      key: client-secret
